=== StefanNRT13417/NRT_134_17/oglasi.dtd
<!ELEMENT oglasi (oglas+)>
<!ELEMENT oglas (kategorija_oglasa,datum_isteka_oglasa,cena,tekst_oglasa,oznake,email_adrese)>
<!ELEMENT kategorija_oglasa EMPTY>
<!ELEMENT datum_isteka_oglasa (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekst_oglasa (#PCDATA)>
<!ELEMENT oznake (oznaka_oglasa+)>
<!ELEMENT email_adrese (email+)>
<!ELEMENT oznaka_oglasa (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ATTLIST kategorija_oglasa kategorija (automobili|stanovi|alati|podučavanje) #REQUIRED>
<!ATTLIST cena valuta (rsd|eur) "rsd">
<!ATTLIST email tip (privatni|sluzbeni) #REQUIRED>

=== StefanNRT13417/NRT_134_17/oglasi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE oglasi SYSTEM "oglasi.dtd">
<oglasi>
	<oglas>
		<kategorija_oglasa kategorija="automobili"/>
		<datum_isteka_oglasa>22.10.2022</datum_isteka_oglasa>
		<cena valuta="eur">2499</cena>
		<tekst_oglasa>Random text</tekst_oglasa>
		<oznake>
			<oznaka_oglasa>BMW</oznaka_oglasa>
			<oznaka_oglasa>M3</oznaka_oglasa>
			<oznaka_oglasa>twin-turbocharged</oznaka_oglasa>
		</oznake>
		<email_adrese>
			<email tip="privatni">randomemail@gmail.com</email>
			<email tip="sluzbeni">randombusinessemail@randomcompany.com</email>
		</email_adrese>
	</oglas>
</oglasi>
